name: Reusable Workflow
on:
  workflow_call:
    secrets:
      PASSWORD:
        description: "Password Description"
        required: true
         
jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print Password
        run: echo '${{ secrets.PASSWORD }}'
      - name: Print GitHub
        run: echo '${{ toJson(github) }}
  checkot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ls -a
